### ISSUE TITLE
Define project scale

### ISSUE THREAD

**Issue by drdanjones** [moj-analytical-services/our-coding-standards#28]
Should we have rough guidelines as to what constitutes a large, medium, small project?

Starter for 10: 
Small - a working version is built in a week, <300 lines of code, all code sensibly contained in one file
Medium - a working version is built in a month, < 800 lines of code, may contain multiple (code) files
Large - a working version takes more than a month, >800 lines of code

**Comment by RobinL** [comment]
Do you mean for the minimum standards?  This is defined in the existing guidance linked here:
https://moj-analytical-services.github.io/our-coding-standards/web/

i.e.
\\dom1\data\HQ\102PF\Shared\Group_LCDSHD2\Analytical Services\AQA - guidance-forms etc\Tailoring Quality Assurance

**Comment by drdanjones** [comment]
Of course, that seems fine.
